CREATE TABLE reassessment (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  diagnosis TEXT,
  present_condition TEXT,
  vitals JSONB,
  bed_sore JSONB,
  mental_status TEXT,
  hygiene TEXT,
  general_status TEXT,
  care_status TEXT,
  outdoor_hours TEXT,
  nursing_diagnosis TEXT,
  follow_up_evaluation TEXT,
  assignment_done_by TEXT,
  allotted_staff_name TEXT,
  assigning_period TEXT,
  previous_visited_date DATE,
  dynamic_fields JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);